<?php

define( 'GLOBEFARER_ROOT', get_template_directory_uri() );
define( 'GLOBEFARER_ROOT_DIR', get_template_directory() );
define( 'GLOBEFARER_ASSETS_ROOT', GLOBEFARER_ROOT . '/assets' );
define( 'GLOBEFARER_ASSETS_ROOT_DIR', GLOBEFARER_ROOT_DIR . '/assets' );
define( 'GLOBEFARER_ASSETS_CSS_ROOT', GLOBEFARER_ASSETS_ROOT . '/css' );
define( 'GLOBEFARER_ASSETS_CSS_ROOT_DIR', GLOBEFARER_ASSETS_ROOT_DIR . '/css' );
define( 'GLOBEFARER_ASSETS_JS_ROOT', GLOBEFARER_ASSETS_ROOT . '/js' );
define( 'GLOBEFARER_ASSETS_JS_ROOT_DIR', GLOBEFARER_ASSETS_ROOT_DIR . '/js' );
define( 'GLOBEFARER_INC_ROOT', GLOBEFARER_ROOT . '/inc' );
define( 'GLOBEFARER_INC_ROOT_DIR', GLOBEFARER_ROOT_DIR . '/inc' );
